In [1]:
import numpy as np

In [2]:
my_arr=np.arange(1000000)

In [3]:
my_list=list(range(1000000))

In [13]:
%time for _ in range(1000000):my_arr2=my_arr*2

Wall time: 132 ms


In [15]:
%time for _ in range(10):my_arr2=[my_arr*2 for my_arr in my_list]

Wall time: 1.02 s


In [16]:
import numpy as np

In [17]:
data=np.random.randn(2,3)

In [18]:
data


array([[-0.02433785, -1.73108291, -0.44472607],
       [-0.4228073 , -0.14674651,  0.78373148]])

In [19]:
data*10

array([[ -0.24337849, -17.31082908,  -4.44726067],
       [ -4.22807299,  -1.46746513,   7.83731478]])

In [20]:
data +data

array([[-0.0486757 , -3.46216582, -0.88945213],
       [-0.8456146 , -0.29349303,  1.56746296]])

In [24]:
arr1=np.array(data1)

In [25]:
arr1

array([6, 6, 7, 8])

In [23]:
data1=[6,6,7,8]

In [26]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
np.zeros((2,5,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [29]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
arr1=np.array([1,2,3],dtype=np.float64)

In [31]:
arr2=np.array([1,2,3],dtype=np.int32)

In [32]:
arr1

array([1., 2., 3.])

In [33]:
arr2

array([1, 2, 3])

In [35]:
float_arr=arr2.astype(np.float64)

In [37]:
arr2.dtype

dtype('int32')

In [38]:
float_arr.dtype

dtype('float64')

In [39]:
int_arr=float_arr.astype(np.int32)

In [40]:
int_arr.dtype

dtype('int32')

In [41]:
int_arr.astype(float_arr.dtype)

array([1., 2., 3.])

In [42]:
empty_uint32=np.empty(8,dtype='u4')

In [43]:
empty_uint32

array([2836620936,        574,    3801155,    5570652,    6619251,
          7536754,    6553692,    7077989], dtype=uint32)

In [48]:
np.empty(6)

array([0.02433785, 1.73108291, 0.44472607, 0.4228073 , 0.14674651,
       0.78373148])

In [85]:
arr=np.array([[1,2,3],[4,5,6]])

TypeError: 'list' object is not callable

In [50]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [52]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [53]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [54]:
arr*0.5

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [81]:
arr2=np.array=([[0,4,1],[7,2,12]])

In [82]:
arr*arr2

ValueError: operands could not be broadcast together with shapes (10,) (2,3) 

In [57]:
arr>arr2

array([[ True, False,  True],
       [False,  True, False]])

In [59]:
arr=np.arange(10)

In [60]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
arr[5]

5

In [62]:
arr[5:9]

array([5, 6, 7, 8])

In [64]:
arr[5:8]=12

In [65]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [66]:
arr_slice=arr[5:8]

In [67]:
arr_slice

array([12, 12, 12])

In [68]:
arr_slice[1]=123456

In [69]:
arr

array([     0,      1,      2,      3,      4,     12, 123456,     12,
            8,      9])

In [70]:
arr_slice[:]=999

In [71]:
arr

array([  0,   1,   2,   3,   4, 999, 999, 999,   8,   9])

In [36]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
arr2d[2]

array([7, 8, 9])

In [1]:
import numpy as np

In [86]:
arr=np.arange(10)

In [87]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
arr=np.array([4])

TypeError: 'list' object is not callable

In [2]:
r=np.array([123])

In [3]:
r

array([123])

In [37]:
arr2d[0][2]

3

In [38]:
arr2d[0,2]

3

In [23]:
arr3d=([[[1,3,3],[4,5,6]],[[7,8,9],[11,12,13]]])

In [22]:
arr3d[0]=78


In [24]:
arr3d

[[[1, 3, 3], [4, 5, 6]], [[7, 8, 9], [11, 12, 13]]]

In [25]:
arr3d[0]

[[1, 3, 3], [4, 5, 6]]

In [26]:
old_values=arr3d[0].copy()

In [27]:
old_values

[[1, 3, 3], [4, 5, 6]]

In [29]:
arr3d[0]=42

In [30]:
arr3d

[42, [[7, 8, 9], [11, 12, 13]]]

In [31]:
arr3d[0]=old_values

In [32]:
arr3d

[[[1, 3, 3], [4, 5, 6]], [[7, 8, 9], [11, 12, 13]]]

In [35]:
arr3d[1][0]

[7, 8, 9]

In [39]:
arr3d[0,1]

TypeError: list indices must be integers or slices, not tuple

In [40]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [41]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr2d[1,:2]

array([4, 5])

In [43]:
arr2d[:2,2]

array([3, 6])

In [44]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [46]:
arr2d[:2,1:]=0

In [47]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [57]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [49]:
data=np.random.randn(7,4)

In [58]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [53]:
data

array([[ 0.20714321, -2.0400376 , -0.12447512, -1.08447616],
       [-2.80955141,  0.78718879,  1.14403723,  1.50851625],
       [-0.25447919, -1.81464804,  0.84402454,  0.0949507 ],
       [ 0.7865546 ,  2.4219381 , -0.70851419, -0.34988345],
       [ 0.98376531, -0.51009961,  0.39499171, -1.95546836],
       [-0.68545153, -0.8632037 ,  0.99919552,  2.17346073],
       [ 0.65300201, -0.30686697, -1.12567986,  0.80130742]])

In [59]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

In [60]:
data[names=='Bob']

array([[ 0.20714321, -2.0400376 , -0.12447512, -1.08447616],
       [ 0.7865546 ,  2.4219381 , -0.70851419, -0.34988345]])

In [56]:
names

'Bob'

In [61]:
data[names=='Bob',2:]

array([[-0.12447512, -1.08447616],
       [-0.70851419, -0.34988345]])

In [62]:
data[names=='Bob',3]

array([-1.08447616, -0.34988345])

In [63]:
names!='Bob'

array([False,  True,  True, False,  True,  True,  True])

In [68]:
data[(names!='Bob')]

array([[-2.80955141,  0.78718879,  1.14403723,  1.50851625],
       [-0.25447919, -1.81464804,  0.84402454,  0.0949507 ],
       [ 0.98376531, -0.51009961,  0.39499171, -1.95546836],
       [-0.68545153, -0.8632037 ,  0.99919552,  2.17346073],
       [ 0.65300201, -0.30686697, -1.12567986,  0.80130742]])

In [69]:
cond=names=='Bob'

In [71]:
data[~(cond)]

array([[-2.80955141,  0.78718879,  1.14403723,  1.50851625],
       [-0.25447919, -1.81464804,  0.84402454,  0.0949507 ],
       [ 0.98376531, -0.51009961,  0.39499171, -1.95546836],
       [-0.68545153, -0.8632037 ,  0.99919552,  2.17346073],
       [ 0.65300201, -0.30686697, -1.12567986,  0.80130742]])

In [72]:
mask=(names=='Bob')|(names=='Will')

In [73]:
mask

array([ True, False,  True,  True,  True, False, False])

In [74]:
data[mask]

array([[ 0.20714321, -2.0400376 , -0.12447512, -1.08447616],
       [-0.25447919, -1.81464804,  0.84402454,  0.0949507 ],
       [ 0.7865546 ,  2.4219381 , -0.70851419, -0.34988345],
       [ 0.98376531, -0.51009961,  0.39499171, -1.95546836]])

In [76]:
data[data>0]=0

In [77]:
data

array([[ 0.        , -2.0400376 , -0.12447512, -1.08447616],
       [-2.80955141,  0.        ,  0.        ,  0.        ],
       [-0.25447919, -1.81464804,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.70851419, -0.34988345],
       [ 0.        , -0.51009961,  0.        , -1.95546836],
       [-0.68545153, -0.8632037 ,  0.        ,  0.        ],
       [ 0.        , -0.30686697, -1.12567986,  0.        ]])

In [78]:
data[1]=1

In [79]:
data

array([[ 0.        , -2.0400376 , -0.12447512, -1.08447616],
       [ 1.        ,  1.        ,  1.        ,  1.        ],
       [-0.25447919, -1.81464804,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.70851419, -0.34988345],
       [ 0.        , -0.51009961,  0.        , -1.95546836],
       [-0.68545153, -0.8632037 ,  0.        ,  0.        ],
       [ 0.        , -0.30686697, -1.12567986,  0.        ]])

In [80]:
arr=np.empty((8,4))

In [81]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])